# creates a ServiceMonitor to scrape off metrics, https is required
# serverName is {app-name}.{namespace}.svc
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cluster-health-analyzer
  namespace: openshift-cluster-health-analyzer
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: cluster-health-analyzer.openshift-cluster-health-analyzer.svc
      certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
      keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-health-analyzer